/** Language-neutral event contract. Params are historical snapshots, never live lookups. */
export const EVENT_TYPES = [
  'TASK_CREATED','TASK_CLAIMED','TASK_ACCEPTED','TASK_ASSIGNED','TASK_REASSIGNED','TASK_AVAILABLE',
  'TASK_DECLINED','TASK_HANDED_BACK','TASK_RETURNED','TASK_UPDATED','TASK_PROGRESS_REPORTED',
  'TASK_SUBMITTED','TASK_RESUMED','TASK_APPROVED','TASK_REWORK','TASK_HANDOFF','TASK_HANDOFF_ASSIGNED',
  'TASK_HANDOFF_AVAILABLE','TASK_CANCELLED','TASK_REOPENED','TASK_REACTIVATED',
  'REDEMPTION_REQUESTED','REDEMPTION_APPROVED','REDEMPTION_CANCELLED','REDEMPTION_READY_FOR_FULFILLMENT',
  'REDEMPTION_FULFILLED','REWARD_CREATED','REWARD_UPDATED','REWARD_ARCHIVED',
  'REWARD_EXECUTORS_UPDATED','REWARD_EXECUTORS_CLEARED','REWARD_CATEGORY_CREATED','REWARD_CATEGORY_UPDATED',
  'REWARD_CATEGORY_ARCHIVED','REWARD_FULFILL_PERMISSION_GRANTED','REWARD_FULFILL_PERMISSION_REVOKED',
  'TASK_REWARD','TASK_PARTIAL_REWARD','TASK_CLAIM_PENALTY','ADMIN_ADJUSTMENT','REDEMPTION','REFUND','REVERSAL',
  'UPLOAD_POLICY_UPDATED',
] as const
export type EventType = typeof EVENT_TYPES[number]
export type EventParams = Record<string, string | number | boolean | null | string[]>
export interface EventRecord { eventType?: string | null; params?: EventParams | null }
export const eventKey = (code: EventType) => 'event.' + code.toLowerCase().replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
