"""initial schema

Revision ID: bce2aa82978d
Revises: 
Create Date: 2026-09-02 12:05:54.359177
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'bce2aa82978d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('object', sa.String(length=400), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('econ', sa.String(length=60), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_company_id'), 'activity', ['company_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('ref', sa.String(length=400), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_company_id'), 'ledger', ['company_id'], unique=False)
    op.create_index(op.f('ix_ledger_user_id'), 'ledger', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=18), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('pri', sa.String(length=12), nullable=True),
    sa.Column('redemption_id', sa.String(length=40), nullable=True),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('redemptions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('reward_id', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemptions_company_id'), 'redemptions', ['company_id'], unique=False)
    op.create_index(op.f('ix_redemptions_user_id'), 'redemptions', ['user_id'], unique=False)
    op.create_table('company_settings',
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('max_submission_total_mb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_company_id'), 'rewards', ['company_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('audience', sa.String(length=12), nullable=False),
    sa.Column('assign_mode', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Float(), nullable=False),
    sa.Column('reported', sa.Float(), nullable=False),
    sa.Column('paid', sa.Float(), nullable=False),
    sa.Column('submission_note', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.Float(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('notif_muted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contributions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=40), nullable=False),
    sa.Column('reported_pct', sa.Float(), nullable=False),
    sa.Column('accepted_pct', sa.Float(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributions_company_id'), 'contributions', ['company_id'], unique=False)
    op.create_index(op.f('ix_contributions_task_id'), 'contributions', ['task_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reported_pct', sa.Float(), nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=12), nullable=False),
    sa.Column('reviewer_id', sa.String(length=40), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_company_id'), 'submissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.create_table('task_cycles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=14), nullable=True),
    sa.Column('paid', sa.Float(), nullable=False),
    sa.Column('verified', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_cycles_company_id'), 'task_cycles', ['company_id'], unique=False)
    op.create_index(op.f('ix_task_cycles_task_id'), 'task_cycles', ['task_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('submission_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_company_id'), 'attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_attachments_submission_id'), 'attachments', ['submission_id'], unique=False)
    op.create_index(op.f('ix_attachments_task_id'), 'attachments', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_task_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_submission_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_company_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_task_cycles_task_id'), table_name='task_cycles')
    op.drop_index(op.f('ix_task_cycles_company_id'), table_name='task_cycles')
    op.drop_table('task_cycles')
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_company_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_contributions_task_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_company_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_rewards_company_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_redemptions_user_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_company_id'), table_name='redemptions')
    op.drop_table('redemptions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ledger_user_id'), table_name='ledger')
    op.drop_index(op.f('ix_ledger_company_id'), table_name='ledger')
    op.drop_table('ledger')
    op.drop_table('companies')
    op.drop_index(op.f('ix_activity_company_id'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
