"""Minimal optional organizational context; preserve all accepted history."""
from alembic import op
import sqlalchemy as sa
revision='ed01c9e2601'
down_revision='ec01c9e2601'
branch_labels=None
depends_on=None

def upgrade():
    op.execute('\nCREATE TABLE teams (\n\tid VARCHAR(40) NOT NULL, \n\tcompany_id VARCHAR(40) NOT NULL, \n\tname VARCHAR(120) NOT NULL, \n\tcreated_at FLOAT NOT NULL, \n\tclosed_at FLOAT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(company_id) REFERENCES companies (id), \n\tCONSTRAINT uq_teams_tenant UNIQUE (company_id, id), \n\tCONSTRAINT ck_teams_time CHECK (closed_at IS NULL OR closed_at >= created_at)\n)\n\n')
    op.execute('CREATE INDEX ix_teams_company_id ON teams (company_id)')
    op.execute('\nCREATE TABLE projects (\n\tid VARCHAR(40) NOT NULL, \n\tcompany_id VARCHAR(40) NOT NULL, \n\tname VARCHAR(120) NOT NULL, \n\tcreated_at FLOAT NOT NULL, \n\tclosed_at FLOAT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(company_id) REFERENCES companies (id), \n\tCONSTRAINT uq_projects_tenant UNIQUE (company_id, id), \n\tCONSTRAINT ck_projects_time CHECK (closed_at IS NULL OR closed_at >= created_at)\n)\n\n')
    op.execute('CREATE INDEX ix_projects_company_id ON projects (company_id)')
    op.execute('\nCREATE TABLE team_memberships (\n\tteam_id VARCHAR(40) NOT NULL, \n\tid VARCHAR(40) NOT NULL, \n\tcompany_id VARCHAR(40) NOT NULL, \n\tuser_id VARCHAR(40) NOT NULL, \n\tmanager BOOLEAN NOT NULL, \n\tjoined_at FLOAT NOT NULL, \n\tleft_at FLOAT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(company_id, team_id) REFERENCES teams (company_id, id), \n\tFOREIGN KEY(company_id, user_id) REFERENCES users (company_id, id), \n\tCONSTRAINT ck_team_membership_time CHECK (left_at IS NULL OR left_at >= joined_at)\n)\n\n')
    op.execute('CREATE INDEX ix_team_membership_history ON team_memberships (company_id, team_id, user_id, joined_at)')
    op.execute('CREATE UNIQUE INDEX uq_active_team_member ON team_memberships (company_id, user_id) WHERE left_at IS NULL')
    op.execute('\nCREATE TABLE project_memberships (\n\tproject_id VARCHAR(40) NOT NULL, \n\tid VARCHAR(40) NOT NULL, \n\tcompany_id VARCHAR(40) NOT NULL, \n\tuser_id VARCHAR(40) NOT NULL, \n\tmanager BOOLEAN NOT NULL, \n\tjoined_at FLOAT NOT NULL, \n\tleft_at FLOAT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(company_id, project_id) REFERENCES projects (company_id, id), \n\tFOREIGN KEY(company_id, user_id) REFERENCES users (company_id, id), \n\tCONSTRAINT ck_project_membership_time CHECK (left_at IS NULL OR left_at >= joined_at)\n)\n\n')
    op.execute('CREATE INDEX ix_project_membership_history ON project_memberships (company_id, project_id, user_id, joined_at)')
    op.execute('CREATE UNIQUE INDEX uq_active_project_member ON project_memberships (company_id, project_id, user_id) WHERE left_at IS NULL')
    op.execute('\nCREATE TABLE organization_event_scopes (\n\tcompany_id VARCHAR(40) NOT NULL, \n\tevent_id VARCHAR(40) NOT NULL, \n\tcaptured_at FLOAT NOT NULL, \n\tbasis JSONB NOT NULL, \n\tteam_id VARCHAR(40), \n\tproject_id VARCHAR(40), \n\tPRIMARY KEY (company_id, event_id), \n\tCONSTRAINT ck_event_context_scope CHECK (team_id IS NULL OR project_id IS NULL), \n\tCONSTRAINT fk_event_context_team FOREIGN KEY(company_id, team_id) REFERENCES teams (company_id, id), \n\tCONSTRAINT fk_event_context_project FOREIGN KEY(company_id, project_id) REFERENCES projects (company_id, id), \n\tFOREIGN KEY(company_id, event_id) REFERENCES canonical_events (company_id, id)\n)\n\n')
    op.execute('\nCREATE TABLE organization_changes (\n\tid VARCHAR(40) NOT NULL, \n\tcompany_id VARCHAR(40) NOT NULL, \n\tactor_id VARCHAR(40) NOT NULL, \n\taction VARCHAR(40) NOT NULL, \n\tdetail JSONB NOT NULL, \n\tcreated_at FLOAT NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(company_id, actor_id) REFERENCES users (company_id, id)\n)\n\n')
    op.execute('CREATE INDEX ix_organization_changes_company_id ON organization_changes (company_id)')
    op.execute("\nCREATE TABLE github_project_attributions (\n\tid VARCHAR(40) NOT NULL, \n\tcompany_id VARCHAR(40) NOT NULL, \n\tsource_id VARCHAR(40) NOT NULL, \n\tresource_kind VARCHAR(20) NOT NULL, \n\tresource_id VARCHAR(20) NOT NULL, \n\tproject_id VARCHAR(40) NOT NULL, \n\tjoined_at FLOAT NOT NULL, \n\tleft_at FLOAT, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(company_id, source_id) REFERENCES github_sources (company_id, id), \n\tFOREIGN KEY(company_id, project_id) REFERENCES projects (company_id, id), \n\tCONSTRAINT ck_github_attribution_kind CHECK (resource_kind IN ('issue','pull_request')), \n\tCONSTRAINT ck_github_attribution_resource CHECK (resource_id ~ '^[1-9][0-9]{0,19}$'), \n\tCONSTRAINT ck_github_attribution_time CHECK (left_at IS NULL OR left_at >= joined_at)\n)\n\n")
    op.add_column('tasks',sa.Column('team_id',sa.String(40),nullable=True))
    op.add_column('tasks',sa.Column('project_id',sa.String(40),nullable=True))
    op.create_check_constraint('ck_task_scope','tasks','team_id IS NULL OR project_id IS NULL')
    op.create_foreign_key('fk_task_team','tasks','teams',['company_id','team_id'],['company_id','id'])
    op.create_foreign_key('fk_task_project','tasks','projects',['company_id','project_id'],['company_id','id'])
    op.add_column('peer_thanks',sa.Column('team_id',sa.String(40),nullable=True))
    op.add_column('peer_thanks',sa.Column('project_id',sa.String(40),nullable=True))
    op.create_check_constraint('ck_thanks_scope','peer_thanks','team_id IS NULL OR project_id IS NULL')
    op.create_foreign_key('fk_thanks_team','peer_thanks','teams',['company_id','team_id'],['company_id','id'])
    op.create_foreign_key('fk_thanks_project','peer_thanks','projects',['company_id','project_id'],['company_id','id'])
    op.add_column('manager_recognitions',sa.Column('team_id',sa.String(40),nullable=True))
    op.add_column('manager_recognitions',sa.Column('project_id',sa.String(40),nullable=True))
    op.create_check_constraint('ck_recognition_scope','manager_recognitions','team_id IS NULL OR project_id IS NULL')
    op.create_foreign_key('fk_recognition_team','manager_recognitions','teams',['company_id','team_id'],['company_id','id'])
    op.create_foreign_key('fk_recognition_project','manager_recognitions','projects',['company_id','project_id'],['company_id','id'])
    op.add_column('help_requests',sa.Column('team_id',sa.String(40),nullable=True))
    op.add_column('help_requests',sa.Column('project_id',sa.String(40),nullable=True))
    op.create_check_constraint('ck_help_scope','help_requests','team_id IS NULL OR project_id IS NULL')
    op.create_foreign_key('fk_help_team','help_requests','teams',['company_id','team_id'],['company_id','id'])
    op.create_foreign_key('fk_help_project','help_requests','projects',['company_id','project_id'],['company_id','id'])
    op.add_column('rules',sa.Column('team_id',sa.String(40),nullable=True))
    op.add_column('rules',sa.Column('project_id',sa.String(40),nullable=True))
    op.create_check_constraint('ck_rule_scope','rules','team_id IS NULL OR project_id IS NULL')
    op.create_foreign_key('fk_rule_team','rules','teams',['company_id','team_id'],['company_id','id'])
    op.create_foreign_key('fk_rule_project','rules','projects',['company_id','project_id'],['company_id','id'])
    op.add_column('policies',sa.Column('team_id',sa.String(40),nullable=True))
    op.add_column('policies',sa.Column('project_id',sa.String(40),nullable=True))
    op.create_check_constraint('ck_policy_scope','policies','team_id IS NULL OR project_id IS NULL')
    op.create_foreign_key('fk_policy_team','policies','teams',['company_id','team_id'],['company_id','id'])
    op.create_foreign_key('fk_policy_project','policies','projects',['company_id','project_id'],['company_id','id'])
    op.execute("\nCREATE OR REPLACE FUNCTION reject_organization_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$\nBEGIN RAISE EXCEPTION 'Organization history is immutable' USING ERRCODE='23514'; END; $$;\nDROP TRIGGER IF EXISTS organization_scope_immutable ON organization_event_scopes;\nCREATE TRIGGER organization_scope_immutable BEFORE UPDATE OR DELETE ON organization_event_scopes\nFOR EACH ROW EXECUTE FUNCTION reject_organization_history_mutation();\nDROP TRIGGER IF EXISTS organization_change_immutable ON organization_changes;\nCREATE TRIGGER organization_change_immutable BEFORE UPDATE OR DELETE ON organization_changes\nFOR EACH ROW EXECUTE FUNCTION reject_organization_history_mutation();\nCREATE UNIQUE INDEX IF NOT EXISTS uq_github_resource_attribution ON github_project_attributions (company_id,source_id,resource_kind,resource_id) WHERE left_at IS NULL;\nCREATE OR REPLACE FUNCTION guard_membership_history() RETURNS trigger LANGUAGE plpgsql AS $$\nBEGIN\n IF TG_OP='DELETE' OR OLD.left_at IS NOT NULL OR NEW.left_at IS NULL OR\n    (to_jsonb(OLD)-'left_at') IS DISTINCT FROM (to_jsonb(NEW)-'left_at') THEN\n  RAISE EXCEPTION 'Membership history is immutable except closing an active interval' USING ERRCODE='23514';\n END IF;\n RETURN NEW;\nEND; $$;\nDROP TRIGGER IF EXISTS github_attribution_history ON github_project_attributions;\nCREATE TRIGGER github_attribution_history BEFORE UPDATE OR DELETE ON github_project_attributions\nFOR EACH ROW EXECUTE FUNCTION guard_membership_history();\nDROP TRIGGER IF EXISTS team_membership_history ON team_memberships;\nCREATE TRIGGER team_membership_history BEFORE UPDATE OR DELETE ON team_memberships\nFOR EACH ROW EXECUTE FUNCTION guard_membership_history();\nDROP TRIGGER IF EXISTS project_membership_history ON project_memberships;\nCREATE TRIGGER project_membership_history BEFORE UPDATE OR DELETE ON project_memberships\nFOR EACH ROW EXECUTE FUNCTION guard_membership_history();\n")

def downgrade():
    if op.get_bind().scalar(sa.text('SELECT EXISTS (SELECT 1 FROM teams) OR EXISTS (SELECT 1 FROM projects) OR EXISTS (SELECT 1 FROM team_memberships) OR EXISTS (SELECT 1 FROM project_memberships) OR EXISTS (SELECT 1 FROM organization_event_scopes) OR EXISTS (SELECT 1 FROM organization_changes) OR EXISTS (SELECT 1 FROM github_project_attributions) OR EXISTS (SELECT 1 FROM tasks WHERE team_id IS NOT NULL OR project_id IS NOT NULL) OR EXISTS (SELECT 1 FROM peer_thanks WHERE team_id IS NOT NULL OR project_id IS NOT NULL) OR EXISTS (SELECT 1 FROM manager_recognitions WHERE team_id IS NOT NULL OR project_id IS NOT NULL) OR EXISTS (SELECT 1 FROM help_requests WHERE team_id IS NOT NULL OR project_id IS NOT NULL) OR EXISTS (SELECT 1 FROM rules WHERE team_id IS NOT NULL OR project_id IS NOT NULL) OR EXISTS (SELECT 1 FROM policies WHERE team_id IS NOT NULL OR project_id IS NOT NULL)')):
        raise RuntimeError('Cannot discard organization configuration or historical context')
    op.drop_constraint('fk_task_team','tasks',type_='foreignkey')
    op.drop_constraint('fk_task_project','tasks',type_='foreignkey')
    op.drop_constraint('ck_task_scope','tasks',type_='check')
    op.drop_column('tasks','team_id')
    op.drop_column('tasks','project_id')
    op.drop_constraint('fk_thanks_team','peer_thanks',type_='foreignkey')
    op.drop_constraint('fk_thanks_project','peer_thanks',type_='foreignkey')
    op.drop_constraint('ck_thanks_scope','peer_thanks',type_='check')
    op.drop_column('peer_thanks','team_id')
    op.drop_column('peer_thanks','project_id')
    op.drop_constraint('fk_recognition_team','manager_recognitions',type_='foreignkey')
    op.drop_constraint('fk_recognition_project','manager_recognitions',type_='foreignkey')
    op.drop_constraint('ck_recognition_scope','manager_recognitions',type_='check')
    op.drop_column('manager_recognitions','team_id')
    op.drop_column('manager_recognitions','project_id')
    op.drop_constraint('fk_help_team','help_requests',type_='foreignkey')
    op.drop_constraint('fk_help_project','help_requests',type_='foreignkey')
    op.drop_constraint('ck_help_scope','help_requests',type_='check')
    op.drop_column('help_requests','team_id')
    op.drop_column('help_requests','project_id')
    op.drop_constraint('fk_rule_team','rules',type_='foreignkey')
    op.drop_constraint('fk_rule_project','rules',type_='foreignkey')
    op.drop_constraint('ck_rule_scope','rules',type_='check')
    op.drop_column('rules','team_id')
    op.drop_column('rules','project_id')
    op.drop_constraint('fk_policy_team','policies',type_='foreignkey')
    op.drop_constraint('fk_policy_project','policies',type_='foreignkey')
    op.drop_constraint('ck_policy_scope','policies',type_='check')
    op.drop_column('policies','team_id')
    op.drop_column('policies','project_id')
    op.execute('DROP FUNCTION reject_organization_history_mutation() CASCADE; DROP FUNCTION guard_membership_history() CASCADE;')
    op.drop_table('github_project_attributions')
    op.drop_table('organization_changes')
    op.drop_table('organization_event_scopes')
    op.drop_table('project_memberships')
    op.drop_table('team_memberships')
    op.drop_table('projects')
    op.drop_table('teams')
